CREATE TABLE Users(
    Id VARCHAR(255) PRIMARY KEY,
    Name VARCHAR(255)  NOT NULL,
    Email VARCHAR(255)   NOT NULL,
    Password VARCHAR(255)   NOT NULL,
    IsDeleted INT DEFAULT 0,
    IsEmailSent INT DEFAULT 0

)
